<?php
$translate=array(
    'language'=>'ru',
    'title'=>'Авторизация и Регистрация Тестовое задание',
    'Choose'=>'Выберите язык',
    'Log in'=>'Войти',
    'Your email'=>'Введите Ваш логин или email',
    'Your password'=>'Введите Ваш пароль',
    'Not a member yet ?'=>'Вы еще не зарегистрированы?',
    'join us'=>'Присоединяйтесь к нам',
    'Your username'=>'Введите Ваш логин',
    'Please confirm your password'=>'Пожалуйста, повторите свой пароль',
    'Sign up'=>'Зарегистрироваться',
    'Already a member ?'=>'Вы уже зарегистрированы?',
    'Go and log in'=>'Войти',
    'Length username should be more than two symbols'=>'Длинна логина должна быть больше двух символов',
    'Length password should be more than 3 symbols'=>'Длинна ппаарроолляя должна быть больше 3-х символов',
    'You entered incorrectly email'=>'Вы ввели некоректный email',
    'Repeat your password correctly'=>'Повторите правильно пароль',
);